// Code generated by github.com/zaaksam/gins/extend/orm/xmodel. DO NOT EDIT.
package model

import "github.com/zaaksam/gins/extend/orm"

func init() {

	orm.Register(&Demo{})

}

// NewDemo 创建数据对象
func NewDemo() *Demo {
	md := &Demo{}
	imd := &md.Model

	md.ID = orm.NewField[uint64](imd, "id", "id", true)

	md.User = orm.NewField[string](imd, "user", "user", false)

	md.Pswd = orm.NewField[string](imd, "pswd", "pswd", false)

	md.Status = orm.NewField[int](imd, "status", "status", false)

	md.Created = orm.NewField[int64](imd, "cteated", "created", false)

	md.Updated = orm.NewField[int64](imd, "updated", "updated", false)

	return md
}
