package command

const genTemplate = `
// Code generated by github.com/zaaksam/gins/extend/orm/xmodel. DO NOT EDIT.
package {{.pkg}}

import "github.com/zaaksam/gins/extend/orm"

{{if .isReg}}
func init() {
	{{range $model := .models}}
	orm.Register(&{{$model.Name}}{})
	{{end}}
}
{{end}}

{{range $model := .models}}
// New{{$model.Name}} 创建数据对象
func New{{$model.Name}}() *{{$model.Name}} {
	md := &{{$model.Name}}{}
	imd := &md.Model

	{{range $field := $model.Fields}}
	md.{{$field.Name}} = orm.NewField[{{$field.RawType}}](imd, "{{$field.XormName}}", "{{$field.JSONName}}", {{$field.IsJSONTagString}})
	{{end}}

	return md
}
{{end}}
`
