package command

const genTemplate = `
// Code generated by github.com/zaaksam/gins/extend/orm/xmodel. DO NOT EDIT.
package {{.pkg}}

import "github.com/zaaksam/gins/extend/orm"

{{if .isReg}}
func init() {
	{{range $model := .models}}
	orm.Register(&{{$model.Name}}{})
	{{end}}
}
{{end}}

{{range $model := .models}}
// New{{$model.Name}} 创建数据对象
func New{{$model.Name}}() *{{$model.Name}} {
	md := &{{$model.Name}}{}
	md.FieldReset()

	return md
}

// FieldReset 重设字段配置
func (md *{{$model.Name}}) FieldReset() {
	if md == nil {
		return
	}

	imd := &md.Model

	{{range $field := $model.Fields}}
	if md.{{$field.Name}} == nil {
		md.{{$field.Name}} = &orm.Field[{{$field.RawType}}]{}
	}
	md.{{$field.Name}}.Reset(imd, "{{$field.XormName}}", "{{$field.JSONName}}", {{$field.IsJSONTagString}})
	{{end}}
}
{{end}}
`
